### ISSUE TITLE
Running bundle exec rspec packs/my_domain fails with cryptic error

### ISSUE THREAD

**Issue by Epigene** [rubyatscale/packs-rails#10] opened 2022-07-15 12:53 UTC
Assuming I have a file structure like described in the readme:

```
packs/
  my_domain/
    spec/ # With stimpack, specs for a pack live next to the pack
      public/
        my_domain_spec.rb
        my_domain/
          my_subdomain_spec.rb
      services/
        my_domain/
          some_private_class_spec.rb
      models/
        some_other_non_namespaced_private_model_spec.rb
        my_domain/
          my_private_namespaced_model_spec.rb
      factories/ # Stimpack will automatically load pack factories into FactoryBot
        my_domain/
          my_private_namespaced_model_factory.rb
```

How do I run the specs at `packs/my_domain/spec/services/my_domain/some_private_class_spec.rb`?

I've tried both:
```
> bundle exec rspec packs/my_domain/spec/services/my_domain/some_private_class_spec.rb
> bundle exec rspec spec/services/my_domain/some_private_class_spec.rb
```

And both result in a very strange error (in fact, with `stimpack` bundled, no specs work any more)

```
An error occurred while loading rails_helper.
Failure/Error: require File.expand_path("../config/environment", __dir__)

NoMethodError:
  undefined method `<<' for nil:NilClass
# ./vendor/bundle/ruby/2.7.0/gems/stimpack-0.4.0/lib/stimpack/integrations/rails.rb:11:in `block (2 levels) in install'
# ./vendor/bundle/ruby/2.7.0/gems/stimpack-0.4.0/lib/stimpack/integrations/rails.rb:10:in `each'
# ./vendor/bundle/ruby/2.7.0/gems/stimpack-0.4.0/lib/stimpack/integrations/rails.rb:10:in `block in install'
# ./vendor/bundle/ruby/2.7.0/gems/stimpack-0.4.0/lib/stimpack/packs.rb:36:in `each_value'
# ./vendor/bundle/ruby/2.7.0/gems/stimpack-0.4.0/lib/stimpack/packs.rb:36:in `each'
# ./vendor/bundle/ruby/2.7.0/gems/stimpack-0.4.0/lib/stimpack/integrations/rails.rb:9:in `install'
# ./vendor/bundle/ruby/2.7.0/gems/stimpack-0.4.0/lib/stimpack.rb:20:in `load'
# ./vendor/bundle/ruby/2.7.0/gems/stimpack-0.4.0/lib/stimpack/railtie.rb:6:in `block in <class:Railtie>'
# ./vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.8/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
# ./vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.8/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
# ./vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.8/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
# ./vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.8/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
# ./vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.8/lib/active_support/lazy_load_hooks.rb:51:in `each'
# ./vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.8/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
# ./vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.8/lib/rails/application.rb:96:in `inherited'
# ./config/application.rb:47:in `<module:ScoutRFP>'
# ./config/application.rb:40:in `<top (required)>'
# ./config/environment.rb:4:in `require'
# ./config/environment.rb:4:in `<top (required)>'
# ./spec/rails_helper.rb:13:in `require'
# ./spec/rails_helper.rb:13:in `<top (required)>'
No examples found.
```

**Comment by Epigene** [comment] 2022-07-19 13:12
Debugging the failing spot, I see that the problem is not with `rspec` or specs themselves, but with app load, even `bundle exec rails routes` fails.

The problem seems to be with `Stimpack.config.paths` returning, among other paths, `"config/routes"` where `app.paths.keys` does not contain it - we have `"config/routes.rb"` instead.

**Comment by ngan** [comment] 2022-07-26 18:23
Hey @Epigene -- Stimpack needs the Rails environment to do its job. I think you test isn't work because you're testing something that doesn't look the rails environment. I'm guessing at the top of `packs/my_domain/spec/services/my_domain/some_private_class_spec.rb` is `require "spec_helper"`? If so, can you change it to `require "rails_helper"` and see if it works?

We can probably make improvements here to not have Stimpack do anything until Rails loads.

**Comment by ngan** [comment] 2022-07-26 18:59
Can you also try adding `require "stimpack"` at the top of your `spec/spec_helper.rb` file?

**Comment by Epigene** [comment] 2022-07-27 08:19
@ngan Thanks for pitching in. Turns out the problem is not with specs at all, as I mentioned in [the update comment](https://github.com/rubyatscale/stimpack/issues/10#issuecomment-1189037030). Something about `Stimpack.config.paths` and routes.

**Comment by noahc** [comment] 2022-08-25 15:10
We're also encountering this problem. I've added `require "stimpack"` at the top of my `spec/spec_helper.rb`

When I run `rspec spec` I get:

```
An error occurred while loading rails_helper.
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

NoMethodError:
  undefined method `<<' for nil:NilClass
# ./config/application.rb:11:in `<module:Mbc>'
# ./config/application.rb:9:in `<top (required)>'
# ./config/environment.rb:2:in `require_relative'
# ./config/environment.rb:2:in `<top (required)>'
# ./spec/rails_helper.rb:3:in `require'
# ./spec/rails_helper.rb:3:in `<top (required)>'
Run options: exclude {:ignore=>true}

```

Here is what my packs folder looks like:

```
❯ tree packs                                                                                                                          
packs
└── bid_bonds
    ├── app
    │   └── models
    │       └── bid_bond.rb
    └── package.yml

3 directories, 2 files
```

If I delete the packs directory completely rspec runs, but fails because it can't find the `BidBond` model. I'm not sure if that is expected or not.

**Comment by noahc** [comment] 2022-08-26 15:07
After a bit more digging, I think this might be a rails 7 vs rails 6.0 issue. On a rails 7 app, `app.paths[path]` in 
the rails.rb file returns a `Rails::Paths::Path` class. In the rails 6 app it returns a nil object.  I haven't tested to see if 6.0 vs 6.1 results in different behavior. 

This change gets it working in Rails 6. But I don't think it actually is a good idea or a long term fix. 

```
 Packs.each do |pack|
   Stimpack.config.paths.each do |path|
     app_path = app.paths.instance_variable_get(:@root)[path]
     next if app_path.nil? # only applies to config/routes
     app_path << pack.path.join(path)
   end
 end
```

**Comment by noahc** [comment] 2022-08-26 16:22
A quick update on this:

After testing various versions of rails, I've determined that you need to be on at least version `6.0.5.1` for the call to app.paths[path] to return the `Rails::Paths::Path` object at all.  However, It is still blowing up when the path from the block tries to call `app.paths['config/routes']` and this returns nil.

**Comment by Epigene** [comment] 2022-08-30 11:31
To follow up, it seems that with upgrade to rails v6.1.6.1 the issue has resolved itself.

`bundle exec rspec packs/my_domain/spec/services/my_domain/some_private_class_spec.rb` runs package specs.

**Comment by AlexEvanczuk** [comment] 2022-08-31 19:15
@noahc @Epigene Can you try upgrading to stimpack 0.7.0 and follow the updated rspec integration notes in the README and let me know if this resolves your issues? If so we can close this out!

**Comment by Epigene** [comment] 2022-09-08 15:31
@AlexEvanczuk Unfortunately it's hard for me to revert to previous Rails version we used to check whether rspec integration tweaks resolved the underlying problem of `app.paths['config/routes` returning `nil`, though I doubt it.
I believe constraining stimpack to require at least ~~Rails~~ autoloading equivalent of Rails v6.0.5.1 would be a more robust approach.
Please, don't make it a dependency on Rails, as I've pointed out in https://github.com/rubyatscale/stimpack/issues/31

**Comment by noahc** [comment] 2022-09-08 16:25
I'll give this a go tomorrow morning and report back my results.

**Comment by AlexEvanczuk** [comment] 2022-09-08 19:04
All good @Epigene -- we feel confident that this fixes the issue without constraining the Rails dependency. I'll address the comment about the Rails dependency in #31, thank you for sharing it 🙏 

Sounds good @noahc

**Comment by noahc** [comment] 2022-09-09 14:24
I upgraded to v0.7.1. I'm still getting the error though as @Epigene pointed out related to `app.paths['config/routes]` returning nil. The general case of not having any `Rails::Paths::Path` object returned prior to v6.0.5.1 is fixed though.

**Comment by noahc** [comment] 2022-09-13 21:46
FWIW, we'll be upgrading to Rails v6.1 in the near future. That should resolve our immediate issues.

**Comment by alexevanczuk** [comment] 2022-09-19 20:16
@noahc Would you be able to provide a minimal reproduction for your issue? If you could do this, then we'll be able to more easily reproduce and fix this issue. The easiest way to do this would be to create a new rails app at the version with the issue and add a dependency on `stimpack`. Ideally we'd like to represent the issue in our test suite, but we don't yet support testing multiple versions of rails.

An alternative solution for us is we can add a minimal gem requirement on `railties` and more explicitly only support 6.1 or above. Let us know what you think!

**Comment by noahc** [comment] 2022-09-22 23:50
@alexevanczuk I attempted to reproduce this with a new rails app running v6.0.5.1 of rails and v0.7.1 of stimpack. I could not. Unfortunately, this leads me to believe that something [Epigene](https://github.com/Epigene) and I have in common with our apps is causing the same issue. I looked through my demo app and production app for any config settings that looked interesting, but didn't see anything that looked promising.

**Comment by OddEssay** [comment] 2022-11-02 21:30
I hit the same issue mentioned here - `app.paths['config/routes]` returning nil - and hacked in a fix by modifying `Stimpack::Integrations::Rails#inject_paths` to just ignore the nil with a guard clause:
```ruby
      def inject_paths
        Packs.all.each do |pack|
          Stimpack.config.paths.each do |path|
            next if @app.paths[path].nil?

            @app.paths[path] << pack.path.join(path)
          end
        end
      end
```

I'm just not sure if that's a good approach, or just masking the actual issue? 🤔

**Comment by OddEssay** [comment] 2022-11-03 23:15
> but @OddEssay do you happen to be using devise?

Yup.

Rails 6.0.6
Devise 4.7.2
Stimpack 0.7.1

When I look for `config/routes`  in our code base I do find the devise comment `# passing skip: :sessions to 'devise_for' in your config/routes.rb`
So, since it might be relevant detail, I have that set to: `config.skip_session_storage = [:http_auth]` in `config/initializers/devise.rb`

**Comment by bmorton** [comment] 2023-01-18 22:28
I just started playing with this gem and I'm running into this on Rails 6.0 too.  We've got an upgrade scheduled for the near future since Rails 6.0 goes EOL in the summer, but in the meantime I added this above our `Application` class in `config/application.rb` and it seems to make things work so far.

```ruby
Packs::Rails.config.paths = %w(
  app
  app/controllers
  app/channels
  app/helpers
  app/models
  app/mailers
  app/views
  lib
  lib/tasks
  config
  config/locales
  config/initializers
  config/routes.rb
)

module AppName
  class Application < Rails::Application
    # ...
  end
end
```

**Comment by alexevanczuk** [comment] 2023-05-02 13:04
Hey all I wanted to know if this is still an issue for folks. It sounds like we have some stop gaps, but we believe that something to do with devise is causing issues. If anyone is able to write a test fixture with rails 6.0 and devise that replicates this issue, we can look deeper into resolving.

**Comment by crystal-williams-brown** [comment] 2023-06-06 23:03
I wonder if this may be related to my issue with rspec https://github.com/rubyatscale/packs-rails/issues/64

It's not recognizing my classes from the pack in the specs.

**Closed** 2024-02-09 21:47 UTC
Labels: bug, documentation
